config/routes.rb
Rails.application.routes.draw do
  resources :articles

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :tags
    = f.text_field :tags
  .actions
    = f.submit 'Save', class: 'btn btn-success'

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles

%table
  %thead
    %tr
      %th Title
      %th Body
      %th Tags
      %th
      %th
      %th

  %tbody
    - @articles.each do |article|
      %tr
        %td= article.title
        %td= article.body
        %td= article.tags
        %td= link_to 'Show', article
        %td= link_to 'Edit', edit_article_path(article)
        %td= link_to 'Destroy', article, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.title
%p
  %b Body:
  = @article.body
%p
  %b Tags:
  = @article.tags

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dockerapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <%= yield %>
</div>

</body>
</html>